export {
  hashPassword, verifyPassword, passwordIsCurrent, validatePassword, validateUsername, generateInitialPassword,
  hasUsers, createUser, authenticateUser, listUsers, getUserById, getUserByUsernameInContainer,
  lookupUserByUsername, updateUser, changePassword, createUserInContainer, countActiveAdmins,
  createSession, getValidSession, deleteSession, purgeExpiredSessions,
  createApiKey, listApiKeysForUser, authenticateApiKey, touchApiKey, revokeApiKey,
  updateApiKeyTier, updateApiKeyLimits, consumeApiKeyQuota,
  createContainer, getContainerById, getContainerByName, listContainers, listActiveContainers,
  banContainer, unbanContainer, deleteContainer, isContainerBanned,
  getContainerAdminsForNotification, markBanNotificationSent,
  getContainerStorageSize, getContainerStatus, listContainerStatuses, isContainerOverLimit,
  getUserContainerId,
  listEmails, addEmail, resendVerificationCode, verifyEmailCode, setPrimaryEmail,
  deleteEmail, getPrimaryEmail, getAnyEmail, hasVerifiedEmail,
  isVerifyEmailOnLogin, setVerifyEmailOnLogin,
  createLoginEmailVerificationSession, consumeLoginEmailVerificationSession, resendLoginEmailVerificationCode,
  generateTotpSecret, enableTotp, disableTotp, verifyTotp,
  createTotpTempToken, consumeTotpTempToken,
  createOperation2FASession, consumeOperation2FASession, resendOperation2FACode, sendOperation2FACode,
  createMfaSession, validateMfaSession, getAvailable2FAMethods,
  listPhones, addPhone, resendPhoneVerificationCode, verifyPhoneCode, setPrimaryPhone,
  deletePhone, getPrimaryPhone, hasVerifiedPhone, maskPhone,
  createResetRequest, getResetRequest, approveResetRequest, purgeExpiredResetTokens,
  createAdminResetSession, consumeAdminResetSession, verifyAdminResetEmailCode,
  writeAuditLog,
} from './auth/index.js';

export type { ApiKeyLimits, ResetRequest } from './auth/index.js';
